build.gradle
jack doesn't produce a classes.jar and is slower than the old toolchain.
=> Stop building with Jack.

build.gradle
-g avoids them but users have to remember to specify that, plus Gradle
warns you that you are calling things in an invalid way unless you request
permissions through the runtime system.
=> Target sdk 22 so we don't have to deal with runtime permissions.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
mIsScanning is unused since mIsScanResultAvailable is used as the internal check.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/32)
=> Remove unused var mIsScanning from WifiManagerSnippet

src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java
Returning boolean is not consistent with our style and is not done for any
other method in MBS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/42)
=> Throw exceptions in case of failure to enable or disable HCI snoop log.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Added an RPC to enable or disable wifi-verbose logging. Only available on API 21+.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/46)
=> Added snippet to enable/disable wifi-verbose logging on API 21+

src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java
btDiscoverAndGetResults() is flaky when set to only wait up to 1 minute for BT scan results.
It often failed with the following exception:
com.google.android.mobly.snippet.bundled.BluetoothAdapterSnippet$BluetoothAdapterSnippetException: Failed to get discovery results after 1 min, timeout!
Increasing the discovery timeout to 2 mins (a BT standard) should fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/49)
=> Increasing btDisoverAndGetResults timeout to 2 minutes

src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java
This is helpful for validating successful pairing when used in conjunction with  btGetPairedDevices()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/50)
=> Adding BT RPC getAddress

src/main/java/com/google/android/mobly/snippet/bundled/utils/MbsEnums.java
This prevents btDiscoverAndGetResults() from failing during the serialization steps when there are "unknown" BT devices present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/63)
=> Added support for Unknown BT device type

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
The official story is that only Settings running as system UID can call them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/66)
=> Remove bt snoop log APIs.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This fixes an issue where calling wifiConnect with no active network silently fails to connect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/70)
=> Check for current network activity before deciding it is already connected

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/NetworkingSnippet.java
Has one method for now, Connectable, that implicitly checks TCP
connectivity to a host and port.
Example usage using snippet_shell:
```
$ snippet_shell -s HTxxxxxxxx  com.google.android.mobly.snippet.bundled
>>> s.networkIsTcpConnectable("www.google.com", 80)
False
>>> s.networkIsTcpConnectable("www.google.com", 80)
True
>>> start = datetime.now() ; s.networkIsTcpConnectable("www.google.com", 81) ; print(datetime.now() - start)
False
0:02:07.438771
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/78)
=> Add a networking snippet module.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/FileSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/NetworkingSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Use Android API to download file using HTTP and store locally. Locally compute MD5 hash and  respond to host with Uri and hash value.
Since current usage of curl does not make use of the downloaded file other than to compute the MD5 hash to, presumably, verify transfer integrity it's not necessary to copy the file to the host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/80)
=> Method to perform HTTP download to local storage.

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/MbsEnums.java
Turns out the TxPower level field in scan record is a `db` value instead of TxPower enum.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/86)
=> Fix a missing value in BleAdvertisingTxPower enum.

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
E.g. if BT was in the process of turning off when we called `btEnable`,
BT would finish turning off before turning on again, but the `btEnable`
call would timeout before that.
Same situation for `btDisable` and wifi toggles.
Also update gradle deps per presubmit requirements.
@k2fong @kdart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/91)
=> Handle a race condition in wifi/bt toggle.

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/FileSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/NetworkingSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/NotificationSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothA2dpSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/105)
=> Migrate to androidx packages

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
* Adopt shell permission in Wi-Fi snippet when it's Q.
* Fix ClassNotFound error caused by androidx
Tested locally and confirmed that the change works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/112)
=> Handle Wi-Fi permission requirements in Q.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
cleanup UiAutomator connection after use.  This will enable other UiAutomator user to properly connect instead of getting an "already registered" exception because UiAutomator only accept a single connection at any giving time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/114)
=> Cleanup UiAutomator connection

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
Add a string length check on the given param to avoid
StringIndexOutOfBoundsException.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/125)
=> Fix exception in "trimQuotationMarks()" method

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothA2dpSnippet.java
A RPC method is used to check A2DP audio path is enabled or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/128)
=> Add a Rpc "btIsA2dpPlaying" to BluetoothA2dpSnippet

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
android api 29+ has changed the BluetoothAdapter.setScanMode signature from (Integer, Integer) to (Integer, Long). change btBecomeDiscoverable to handle different api level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/129)
=> update btBecomeDiscoverable to handle api level

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Sometimes, a removeNetwork call could remove more than one configured network at a time (e.g. a network and its OWE config), so that the subsequent call may find its target config missing and return false. Currently, this will cause an exception to be raised, even though the intended outcome is achieved. Therefore, it is more reliable to simply verify that the configured network list is cleared by the end of the removal process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/146)
=> Have wifiClearConfiguredNetworks re-check network list to determine operation success.

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
The "BluetoothAdapter#setScanMode" API is no longer accessible to SDK versions 31 and above. Add a intent-based workflow according to https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#ACTION_REQUEST_DISCOVERABLE. Use UI Automator to interact with the pop-up user dialog.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/149)
=> Use intent to enable BT discoverability for T+; handle dialog with UIAutomator

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/AndroidManifest.xml
1. Update JCenter to Maven Central as JCenter is shutting down in September 2022
2. Update Gradle from 4 (2017) to 7 (2022)
3. Update minSdkVersion from 18 to 26
4. Update targetSdkVersion from 22 to 31
5. Update AndroidX Test Library from 1.3.0 (2020) to 1.5.2 (2023)
6. Update Mobly Snippet Lib from 1.2.0 (2017) to 1.4.0 (2023)
7. Update Error Prone Annotations from 2.5.1 (2021) to 2.15.0 (2022)
8. Add MultiDex to fix `androidx.multidex.MultiDexApplication` missing issue
9. Add android.permission.BLUETOOTH_ADVERTISE permission for BLE advertising
10. Add android.permission.BLUETOOTH_SCAN permission for BLE scan
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippe …
=> Modernize MBS including SDK version, dependencies and permissions

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/BluetoothLeAdvertiserSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/BluetoothLeScannerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothGattClientSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothGattServerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/DataHolder.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/MbsEnums.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/RpcEnum.java
1. Support passing `scanResponse` to BLE advertising.
2. Support passing `scanFilters` and `scanSettings` to BLE scanning.
3. Support BluetoothGatt APIs.
4. Support BluetoothGattServer APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/167)
=> Support more features on BLE related API.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/PairingBroadcastReceiver.java
- StaticQualifiedUsingExpression: Static method serializeBluetoothDevice should not be accessed from an object instance; instead use JsonSerializer.serializeBluetoothDevice
- MissingOverride: onReceive implements method in BroadcastReceiver; expected @Override
- RemoveUnusedImports: Unused imports: java.lang.reflect.InvocationTargetException, java.lang.reflect.Method
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/178)
=> Fix Error Prone

src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
getCallState was deprecated, use getCallStateForSubscription to get the call state.
https://developer.android.com/reference/android/telephony/TelephonyManager#getCallState%28%29
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/180)
=> Update version check for deprecated getCallState and getNetworkType

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java
`manufacturerSpecificData` is one of arguments when adding manufacturer specific data (see [AdvertiseData.Builder#addManufacturerData](https://developer.android.com/reference/android/bluetooth/le/AdvertiseData.Builder#public-methods_1))
Before Change:
```
ad.mbs.bleStartAdvertising(
advertiseSettings,
{
'IncludeDeviceName': True,
'ManufacturerData': {'ManufacturerId': 224},
'ManufacturerSpecificData': '[0x78, 0x01]',
},
)
```
After Change:
```
ad.mbs.bleStartAdvertising(
advertiseSettings,
{
'IncludeDeviceName': True,
'ManufacturerData': {
'ManufacturerId': 224,
'ManufacturerSpecificData': '[0x78, 0x01]',
},
},
)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-s …
=> Refactor manufacturerSpecificData to ManufacturerSpecificData

src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
```
src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java:50: error: package Build does not exist
if (Build.VERSION.SDK_INT < 31) {
^
src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java:62: error: package Build does not exist
if (Build.VERSION.SDK_INT < 30) {
^
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/181)
=> Fix error: package Build does not exist

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
1. To address deprecated API: [public String getLine1Number ()](https://developer.android.com/reference/android/telephony/TelephonyManager#getLine1Number())
2. To allow access to multi-sim device:
2.1. Add new function: String getPhoneNumber(int simSlot)
2.2. Add new variant: int getTelephonyCallState(int simSlot)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/182)
=> Update deprecated API and allow access to dual-sim device

src/main/AndroidManifest.xml
https://developer.android.com/develop/connectivity/bluetooth/bt-permissions
Context:
```
Android 12 (S) and later: Google introduced significant changes to Bluetooth permissions. The older permissions BLUETOOTH and BLUETOOTH_ADMIN were replaced by two finer-grained permissions:
- BLUETOOTH_SCAN: Allows apps to scan for nearby Bluetooth devices without having to connect to them.
- BLUETOOTH_CONNECT: Allows apps to connect with paired Bluetooth devices.
```
Add `android:maxSdkVersion="30"` for legacy Bluetooth permissions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/186)
=> Update AndroidManifest.xml to request legacy Bluetooth permissions on older devices

src/main/AndroidManifest.xml
Currently, no toast will occur on Android screen if we build the MBS app via `gradlew`.
As shown in the logcat, the toast is suppressed silently.
```
07-02 10:41:49.831  1399  4652 E NotificationService: Suppressing toast from package com.google.android.mobly.snippet.bundled by user request.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/196)
=> Add the permission to post notification.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Use the network callback for wifi connection status check for L+ devices.
Also remove networkId check for pre-L devices as it doesn't sometimes work while the network is already connected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/195)
=> Add the network callback for wifi connection check

src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
An instrumented context's getApplicationContext() may return null and throw.
In particular this can happen when using the BluetoothAdapterSnippet. Instead we get the applicationInfo from the packageManager.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/199)
=> Fix MBS Utils to work while being instrumented

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change can reduce the flakiness caused by device slowness.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/212)
=> Extend UI wait time for BT action to 2 seconds

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/AndroidManifest.xml, src/test/java/UtilsTest.java
After updating the Gradle and AGP version to the latest and replacing the outdated API `Truth.assertThat#isSameAs`, the APK is now able to be built via Android Studio and gradlew tool.
Fixes #213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/214)
=> Upgrade Gradle version to 8.11 and AGP version to 8.7.3

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java
Reverts google/mobly-bundled-snippets#224 due to builder error
```
src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java:135: error: cannot find symbol
MbsEnums.BLE_PROPERTY_TYPE.getIntBitwiseOr(jsonObject.getString("Properties")),
^
symbol:   method getIntBitwiseOr(String)
location: variable BLE_PROPERTY_TYPE of type RpcEnum
src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java:138: error: cannot find symbol
MbsEnums.BLE_PERMISSION_TYPE.getIntBitwiseOr(jsonObject.getString("Permissions")));
^
symbol:   method getIntBitwiseOr(String)
location: variable BLE_PERMISSION_TYPE of type RpcEnum
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Revert "Update JsonDeserializer::jsonToBluetoothGattCharacteristic"

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/utils/MbsEnums.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/RpcEnum.java, src/test/java/MbsEnumsTest.java
Change `property` and `permission` fields to plural in `BluetoothGattCharacteristic`.
Because multiple BluetoothGattCharacteristic can be contained in one event field.
https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/223)
=> Add RpcEnum::getIntBitwiseOr() Helper API (1/3)

src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java
The new RPCs can be used to check the current audio route playing on the Android system.
For example, when playing a media over a Bluetooth headset, `mediaGetLiveAudioRouteType()` will return [DEVICE_TYPE_BLUETOOTH](https://developer.android.com/reference/android/media/MediaRouter.RouteInfo#DEVICE_TYPE_BLUETOOTH).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/232)
=> Add new RPCs for checking live audio route info

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java
Example usage:
```
ad.mbs.wifiConnect({'SSID': 'MyWiFi', 'BSSID': 'a1:b2:c3:d4:e5:f6'}, 'password': '12345678')
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/233)
=> Support for specifying BSSID in Wi-Fi config

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
When Bt bonds over LE the, getAddress() on btGetPairedDevices() will return a randomized bt address. This causes asserts in bt bonding because the device is comparing the randomized public address with its private identity address. Adding the identity address in the bluetooth device bundle will allow validation that devices are bonded
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/236)
=> Include IdentityAddress for BluetoothDevice in JsonSerializer.java

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonDeserializer.java, src/test/java/JsonDeserializerTest.java
This PR adds support to adding descriptors to a BluetoothGattCharacteristic.
See:
* https://developer.android.com/reference/android/bluetooth/BluetoothGattDescriptor#BluetoothGattDescriptor(java.util.UUID,%20int)
* https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic#addDescriptor(android.bluetooth.BluetoothGattDescriptor)
Descriptors are needed to support GATT notifications/indications.
Validated by adding unit tests and running on device and confirming that GATT notifications work
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/239)
=> Add BluetoothGattDescriptor support

src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
Changes:
- Update getLine1Number to first attempt fetching the phone number for the specified simSlot using the active subscription instead of using the outdated TelephonyManager.getLine1Number() method.
- Add a fallback mechanism to retrieve the phone number from the default subscription if the slot-specific attempt yields a null or empty result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/246)
=> Refactor `TelephonySnippet#getLine1Number` for improved reliability.
