build.gradle
=> Fix snippet lib dep.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/NotificationSnippet.java
=> Add makeToast.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/16)
=> Support adding and listing Google accounts.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/14)
=> Add some simple telephony and audio controls to MBS.

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/21)
=> Add macOS index file to gitignore.

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
AudioManager.NUM_STREAMS is deprecated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/22)
=> Get the number of streams for muting through reflection.

src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/23)
=> remove unused imports in AudioSnippet

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/25)
=> Adding content sync controls to AccountSnippet.

src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java
Fixes invalid formatting in AccountSnippet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/30)
=> Run googleJavaFormat.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
* also fix lint in AccountSnippet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/28)
=> Allow calling wifiConnect with the connected network.

src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
Four methods added:
public void bluetoothStartDiscovery()
public JSONArray bluetoothGetCachedScanResults()
public JSONArray bluetoothDiscoveryAndGetResults() // it calls the above two methods
public JSONArray bluetoothGetPairedDevices()
One class added:
private class BluetoothScanReceiver extends BroadcastReceiver{} // used for discovery
One serializer added:
private JSONObject serializeBtDevice(BluetoothDevice data)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/26)
=> adding methords for BluetoothAdapterSnippet with serializer

src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Fixes #36.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/37)
=> Squash "serializable class has no definition of serialVersionUID" warning.

build.gradle, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/38)
=> Gradle updates suggested by Android studio.

src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/39)
=> Add Rpcs for enabling/disabling bt snoop log.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/ApiVersionException.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Also a change in wait util to accomodate lambda functions that
throw exceptions, which interrupt the wait.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/35)
=> Add Wi-Fi soft ap related Rpc methods.

src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
* Replace ints with proper references.
* Remove fields not supported by API level 11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/34)
=> Fixes in `serializeBluetoothDevice`.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/41)
=> Add Bluetooth Rpcs needed to support making the device discoverable.

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java, src/test/java/UtilsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/45)
=> Simplify API required to call methods by reflection.

build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/48)
=> Update toolchain version.

src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/53)
=> Microphone mute RPCs

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/LogSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/52)
=> Add Rpcs for basic Android logging.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/PairingBroadcastReceiver.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothA2dpSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
* Add support for pairing/unpairing a device.
* Add support for connecting with A2DP profile.
* Reorganize Bluetooth related snippets for future expansion of profile support.
* Use Bundle instead of JSONObject for BluetoothDevice serialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/54)
=> Add basic Bluetooth pairing and A2DP connection features.

src/main/AndroidManifest.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/57)
=> Add MODIFY_AUDIO_SETTINGS for setMicrophoneMute

build.gradle
Verified that linter and build work fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/56)
=> Update toolchain version per Android Studio prompt.

build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/58)
=> Make all warnings abort compilation

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/55)
=> Add method to clear configured networks

src/main/java/com/google/android/mobly/snippet/bundled/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
Success case should not throw exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/61)
=> Minor bug fix to btUnpairedDevice()

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java
Provides 3 methods: 
reset (brings the player back into idle mode)
playAudioFile (plays an audio file from external storage)
stop (stops the existing snippet playback)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/62)
=> Initial audio playback functionality

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/65)
=> Add an rpc to check if wifi is enabled.

src/main/java/com/google/android/mobly/snippet/bundled/MediaSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/67)
=> Run linter on MediaSnippet.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/68)
=> Do not attempt to modify a network in wifiConnect.

src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java
Cleanup style stuff in SmsSnippet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/72)
=> SmsSnippet cleanup

build.gradle
This lib includes the new launch protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/73)
=> Upgrade MBS to using snippet lib 1.2.

src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Add sync version of waitForSms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/76)
=> Add sync waitForSms

README.md, build.gradle, src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/FileSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/NetworkingSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Make changes, or ignore as required.
Also updates some dependency versions, as it requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/81)
=> Make linter happy.

README.md, build.gradle, src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/FileSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/NetworkingSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Reverts google/mobly-bundled-snippets#81
Reverting due to #83 and #84
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/85)
=> Revert "Make linter happy."

README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/FileSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/NetworkingSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
Make everything the current recommended version. 
build and presubmit phase passes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/87)
=> Fix version warnings for gradle builds

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/92)
=> `wifiConnect` should fail if the network specified does not exist.

src/main/java/com/google/android/mobly/snippet/bundled/NotificationSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/93)
=> Use annotation instead of executor for `makeToast`.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/94)
=> Fix typo in wifiConnect.

build.gradle
Quiets presubmit lints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/96)
=> Update gradle versions.

src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/95)
=> Add functionality to specify timeout for waitForSms.

build.gradle, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/97)
=> Update gradle version and deps.

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/98)
=> Add bt cancel discovery.

src/main/AndroidManifest.xml
foo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/100)
=> Use multidex

src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/102)
=> Add RPCs to get/set voice call stream volume

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/FileSnippet.java
and correct a typo of the application package path
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/106)
=> Remove an unused inner class.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/107)
=> Add an API to check if 5G Wi-Fi is supported.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/108)
=> Add api to remove account.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Also improve a log line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/109)
=> Fix a potentialy NPE in wifiConnect.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/110)
=> Remove unnecessary `toString`.

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/117)
=> fixed lint errors on uiautomation connection cleanup

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHearingAidSnippet.java
Fixes suggested by code analyzers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/122)
=> Fix "JavaCodeClarity" problem for BluetoothHearingAidSnippet

build.gradle, src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/UiautomatorSnippet.java
Add a snippet to dump UI hierarchy XML.
- Use uiautomator 2.2 
- Change minSdkVersion from 15 to 18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/132)
=> Add uiautomator snippet.

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change should prevent bluetooth failures during turning On/Off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/134)
=> Refactored bluetooth enable/disable method RPCs

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/138)
=> Additional condition to allow wifi connection to fully take place.

.gitignore, build.gradle, gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/139)
=> Refresh mbs project with latest gradle, build tools and dependencies.

src/main/java/com/google/android/mobly/snippet/bundled/AccountSnippet.java
Replaced "whitelist" with a more respectful term: allowlist.
https://developers.google.com/style/word-list?hl=zh-tw#blacklist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/140)
=> Fix respuctful coding

src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/141)
=> Gets data and voice network type from TelephonyManager.

src/main/java/com/google/android/mobly/snippet/bundled/TelephonySnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/143)
=> Remove trailing spaces.

src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
active.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/144)
=> Add AudioManager#isMusicActive to check whether or not any music is

src/main/java/com/google/android/mobly/snippet/bundled/AudioSnippet.java
Adds getAlarmVolume, getAlarmMaxVolume, setAlarmVolume, muteAlarm for the stream type STREAM_ALARM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/147)
=> Adds stream type STREAM_ALARM methods.

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/utils/RpcEnum.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/148)
=> Replace deprecated ImmutableBiMap#build call; update Guava version to 31.0.1

src/main/java/com/google/android/mobly/snippet/bundled/utils/RpcEnum.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/150)
=> Remove unused minSdk param from RpcEnum

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/152)
=> Fix comment in btBecomeDiscoverable

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/151)
=> Add intent-based flow to enable Bluetooth for T and above.

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/155)
=> Add ScanRecord#getManufacturerSpecificData() to BLE Scan result.

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/157)
=> Fix Error Prone StaticAssignmentInConstructor

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java
1. Add READ_CONTACTS permission for getting accounts on Android O or above.
2. Apply FLAG_IMMUTABLE for sending SMS on Android S or above
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/168)
=> Update permission and flag for Android O+

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/171)
=> Support for clicking the "OK" button on the watch in btBecomeDiscoverable API

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/PairingBroadcastReceiver.java, src/main/java/com/google/android/mobly/snippet/bundled/utils/Utils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/169)
=> Solve permission issues when performing btDiscoverAndGetResults

src/main/java/com/google/android/mobly/snippet/bundled/SmsSnippet.java
Tested locally
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/176)
=> Add RECEIVER_EXPORTED flag to portrait sys ui register receiver calls;

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetClientSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/profiles/BluetoothHeadsetSnippet.java
The class provides functionality for:
Setting connection policies
Connecting and disconnecting from remote devices
Retrieving connection states
Managing voice recognition
Includes methods like:
btHeadsetClientSet
btHfp-connect
btHfp-disconnect
btHfp-getConnectionState
btHfp-startVoiceRecognition
btHfp-stopVoiceRecognition
Also utilizes BroadcastReceiver for handling Bluetooth events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/189)
=> Introduces BluetoothHeadsetSnippet for interacting with the Bluetooth Headset profile(HFP).

build.gradle
Forked from #194 as it hasn't been updated for two months.
Fixes #193.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/198)
=> Fix the error that class "kotlin.jvm.internal.Lambda" not found.

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/ContentProviderOperationSnippet.java
Example usage:
```py
ad.mbs. addGoogleContact('new.contact2@gmail.com', 'my.email@gmail.com')
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/203)
=> Add new snippet for adding a contact with the given email address

src/main/AndroidManifest.xml, src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/207)
=> Add WifiAwareManagerSnippet

src/main/java/com/google/android/mobly/snippet/bundled/WifiAwareManagerSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/209)
=> Rename RPC methods with wifi prefix.

src/main/java/com/google/android/mobly/snippet/bundled/ContactSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/204)
=> Add new snippet for removing a contact with the given email address

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/210)
=> Remove unused android.content.pm.PackageManager

src/main/java/com/google/android/mobly/snippet/bundled/WifiManagerSnippet.java
Add P2P support check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/217)
=> Add P2P support check

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothGattClientSnippet.java, src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothGattServerSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/219)
=> Add requestMtu() API

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothGattServerSnippet.java
https://developer.android.com/reference/android/bluetooth/BluetoothGattServer#cancelConnection(android.bluetooth.BluetoothDevice)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/221)
=> Add rpc for BluetoothGattServer::cancelConnection API

src/test/java/JsonDeserializerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/235)
=> Add Unit Test for JsonDeserializer.java

src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
Reintroduce https://github.com/google/mobly-bundled-snippets/pull/236 guarded behind sdk version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/238)
=> Update JsonSerializer.java to include BLE Identity Address

build.gradle, src/main/java/com/google/android/mobly/snippet/bundled/utils/JsonSerializer.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/240)
=> Update compile SDK to 36 and add permission check when calling BluetoothDevice#getIdentityAddressWithType

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothGattServerSnippet.java
This API is used to send data, via bluetooth gatt, from one device to another. The receiving device will receive a gatt notification or indication (based on the `confirm` param) that data has been received.
See: https://developer.android.com/reference/android/bluetooth/BluetoothGattServer#notifyCharacteristicChanged(android.bluetooth.BluetoothDevice,%20android.bluetooth.BluetoothGattCharacteristic,%20boolean,%20byte[])
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/241)
=> Add snippet for bleNotifyCharacteristicChanged

src/main/java/com/google/android/mobly/snippet/bundled/bluetooth/BluetoothAdapterSnippet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/mobly-bundled-snippets/243)
=> Refactor btBecomeDiscoverable logic under SDK 31
